### ISSUE TITLE
floating point math

### ISSUE THREAD

**Issue by kp666** [vinayjs/calculator#1]
0.1+0.2 should give 0.3 not 0.30000000000000004

**Comment by vinayjs** [comment]
Hey bro ..Thanks for looking into my repo...just noticed the mail now...and
it seemed like a simple issue to hear but was a bit
confusing.............but fixed || mayb.
(looking for more advices and help ......as time is getting tough
watching tutorials(hell), reading pdfs and coding..coding....
two months of coding/learning down and many many many to go..).
